[default]
description = "Default permissions for the settings plugin"
permissions = [
    "allow-load-settings",
    "allow-update-settings",
    "allow-save-window-position",
    "allow-get-system-accent-color",
    "allow-list-custom-themes",
    "allow-save-custom-theme",
    "allow-delete-custom-theme",
]
